-- SQL Script to populate Supabase with mock profiles for testing
-- Run this in Supabase SQL Editor
-- Note: These profiles use fake UUIDs. In production, profiles must be linked to auth.users

-- First, temporarily disable RLS to insert test data
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;

-- Insert mock profiles
INSERT INTO profiles (
  id,
  linkedin_id,
  linkedin_profile_url,
  full_name,
  date_of_birth,
  profile_photo_url,
  city,
  state,
  job_title,
  company,
  industry,
  bio,
  budget_min,
  budget_max,
  move_in_date,
  move_in_flexible,
  work_schedule,
  is_active,
  is_verified,
  profile_completed
) VALUES
(
  '00000000-0000-0000-0000-000000000001',
  'sarah-chen-123',
  'https://www.linkedin.com/in/sarah-chen-123/',
  'Sarah Chen',
  '1998-05-15',
  'https://i.pravatar.cc/300?img=1',
  'San Francisco',
  'CA',
  'Product Designer',
  'Meta',
  'Technology',
  'Passionate product designer with 5 years of experience creating user-centered designs. Love hiking, cooking, and exploring new coffee shops. Looking for a roommate who values cleanliness and quiet evenings. I work hybrid and enjoy hosting small dinner parties on weekends.',
  1800,
  2500,
  '2024-03-01',
  true,
  'hybrid',
  true,
  true,
  true
),
(
  '00000000-0000-0000-0000-000000000002',
  'michael-rodriguez-456',
  'https://www.linkedin.com/in/michael-rodriguez-456/',
  'Michael Rodriguez',
  '1997-08-22',
  'https://i.pravatar.cc/300?img=12',
  'San Francisco',
  'CA',
  'Data Scientist',
  'Netflix',
  'Technology',
  'Data scientist passionate about machine learning and analytics. I enjoy playing guitar, going to concerts, and trying new restaurants. Prefer a clean living space and someone who respects quiet hours. I work remotely most days and love having roommates who are social but also value personal space.',
  2000,
  2800,
  '2024-02-15',
  false,
  'remote',
  true,
  true,
  true
),
(
  '00000000-0000-0000-0000-000000000003',
  'emily-park-789',
  'https://www.linkedin.com/in/emily-park-789/',
  'Emily Park',
  '1999-11-03',
  'https://i.pravatar.cc/300?img=5',
  'San Francisco',
  'CA',
  'Software Engineer',
  'Apple',
  'Technology',
  'Full-stack engineer building amazing products. Love yoga, reading, and exploring the city. Looking for a roommate who is tidy, respectful, and enjoys occasional movie nights. I work in-office 3 days a week and appreciate a quiet home environment for focused work.',
  1900,
  2600,
  '2024-03-15',
  true,
  'hybrid',
  true,
  false,
  true
),
(
  '00000000-0000-0000-0000-000000000004',
  'david-kim-321',
  'https://www.linkedin.com/in/david-kim-321/',
  'David Kim',
  '1996-02-18',
  'https://i.pravatar.cc/300?img=15',
  'San Francisco',
  'CA',
  'Product Manager',
  'Google',
  'Technology',
  'Product manager with a passion for building products that matter. Enjoy rock climbing, cooking, and board games. Looking for a roommate who is clean, communicative, and enjoys social activities. I work hybrid and love hosting game nights with friends.',
  2100,
  2900,
  '2024-02-01',
  false,
  'hybrid',
  true,
  true,
  true
),
(
  '00000000-0000-0000-0000-000000000005',
  'jessica-martinez-654',
  'https://www.linkedin.com/in/jessica-martinez-654/',
  'Jessica Martinez',
  '1998-07-25',
  'https://i.pravatar.cc/300?img=9',
  'San Francisco',
  'CA',
  'UX Researcher',
  'Airbnb',
  'Technology',
  'UX researcher focused on understanding user behavior. Love photography, traveling, and trying new cuisines. Prefer a clean and organized living space. I work remotely and enjoy having roommates who are friendly but respect boundaries. Looking for someone who values communication and shared responsibilities.',
  1850,
  2550,
  '2024-03-01',
  true,
  'remote',
  true,
  true,
  true
),
(
  '00000000-0000-0000-0000-000000000006',
  'alex-thompson-987',
  'https://www.linkedin.com/in/alex-thompson-987/',
  'Alex Thompson',
  '1997-12-10',
  'https://i.pravatar.cc/300?img=20',
  'San Francisco',
  'CA',
  'Backend Engineer',
  'Stripe',
  'Technology',
  'Backend engineer building scalable systems. Enjoy running, reading sci-fi, and playing video games. Looking for a roommate who is clean, quiet during work hours, and enjoys occasional conversations. I work fully remote and appreciate a peaceful home environment.',
  2000,
  2700,
  '2024-02-20',
  true,
  'remote',
  true,
  false,
  true
),
(
  '00000000-0000-0000-0000-000000000007',
  'maya-patel-147',
  'https://www.linkedin.com/in/maya-patel-147/',
  'Maya Patel',
  '1999-04-08',
  'https://i.pravatar.cc/300?img=25',
  'San Francisco',
  'CA',
  'Frontend Engineer',
  'Figma',
  'Technology',
  'Frontend engineer passionate about creating beautiful user interfaces. Love painting, hiking, and trying new restaurants. Looking for a roommate who is tidy, respectful, and enjoys social activities. I work hybrid and love having roommates who are friendly and communicative.',
  1950,
  2650,
  '2024-03-10',
  true,
  'hybrid',
  true,
  true,
  true
),
(
  '00000000-0000-0000-0000-000000000008',
  'ryan-wilson-258',
  'https://www.linkedin.com/in/ryan-wilson-258/',
  'Ryan Wilson',
  '1996-09-14',
  'https://i.pravatar.cc/300?img=30',
  'San Francisco',
  'CA',
  'DevOps Engineer',
  'Amazon',
  'Technology',
  'DevOps engineer focused on infrastructure and automation. Enjoy cycling, cooking, and watching sports. Prefer a clean living space and someone who respects quiet hours. I work in-office most days and appreciate roommates who are social but also value personal space.',
  2050,
  2750,
  '2024-02-25',
  false,
  'in-office',
  true,
  true,
  true
)
ON CONFLICT (id) DO NOTHING;

-- Re-enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Verify the insert
SELECT id, full_name, company, city, state FROM profiles WHERE id LIKE '00000000-%';

